export const USER_ROLES = {
  CITIZEN: "CITIZEN",
  BUSINESS: "BUSINESS",
  LOCAL_AUTHORITY: "LOCAL_AUTHORITY",
  JIRAMA: "JIRAMA",
  NGO: "NGO",
  ENERGY_PROVIDER: "ENERGY_PROVIDER",
  WATER_DELIVERY: "WATER_DELIVERY",
  METEOROLOGIST: "METEOROLOGIST",
  ADMIN: "ADMIN",
};

export const ISSUE_TYPES = {
  WATER_OUTAGE: "WATER_OUTAGE",
  ELECTRICITY_OUTAGE: "ELECTRICITY_OUTAGE",
  LOW_WATER_PRESSURE: "LOW_WATER_PRESSURE",
  POWER_FLUCTUATION: "POWER_FLUCTUATION",
};

export const MAP_INITIAL_REGION = {
  latitude: -18.8792,
  longitude: 47.5079,
  latitudeDelta: 0.0922,
  longitudeDelta: 0.0421,
};
